### ISSUE TITLE
CardMachineRequestorInfo has no public properties and CardPresentPaymentInfo is missing off payment method details

### ISSUE THREAD

**Issue by lewis-green** [dojo-engineering/Dojo.Net.EPOS#1] opened 2023-06-12 10:46 UTC
We've hit a few issues using this SDK for Tables.

1. CardMachineRequestorInfo  has all of it's properties missing public.
2. PaymentMethodDetails has CardPresentPaymentInfo missing

**Comment by AleksandrMalafeev** [comment] 2023-06-12 21:21
Hi Lewis, thanks for reporting the issue. We will fix it ASAP!

**Comment by AleksandrMalafeev** [comment] 2023-06-13 08:32
Hi Lewis, the issue is fixed now, please update to version 1.0.4
Let me know if you have any questions or more issues.

**Closed as completed by AleksandrMalafeev** 2023-06-13 08:32 UTC
